export const options = [
  { name: "Tähitud postiga", price: "€2.95" },
  { name: "Omniva pakiautomaat (Eesti)", price: "€2.95" },
  { name: "Järele tulemisega", price: "€0" },
  { name: "International", price: "€12" },
  { name: "European", price: "€8" },
  { name: "Itella pakiautomaat (Soome)", price: "€8" },
  { name: "Omniva pakiautomaat (Läti)", price: "€8" },
  { name: "Omniva pakiautomaat (Leedu)", price: "€8" }
];

export const pickupLocations = [
  "Ahtme Grossi pakiautomaat",
  "Antsla Konsumi pakiautomaat",
  "Aravete Meie kaupluse pakiautomaat",
  "Aruküla Konsumi pakiautomaat",
  "Aseri Grossi pakiautomaat",
  "Audru osavallakeskuse pakiautomaat",
  "Elva Arbimäe Konsumi pakiautomaat",
  "Elva Turuplatsi Konsumi pakiautomaat",
  "Haabneeme Konsumi pakiautomaat",
  "Haapsalu Kastani pakiautomaat",
  "Haapsalu Konsumi pakiautomaat",
  "Haapsalu Uuemõisa Konsumi pakiautomaat",
  "Haljala Grossi pakiautomaat",
  "Häädemeeste Coop pakiautomaat",
  "Ihaste Konsumi pakiautomaat",
  "Iisaku Grossi pakiautomaat",
  "Järva-Jaani Grossi pakiautomaat",
  "Järvakandi Kandi Konsumi pakiautomaat",
  "Jõgeva Postkontori pakiautomaat",
  "Jõhvi Grossi pakiautomaat",
  "Jõhvi Jewe kaubanduskeskuse pakiautomaat",
  "Jõhvi Maxima XX pakiautomaat",
  "Jõhvi Pargi keskuse pakiautomaat",
  "Jüri Grossi pakiautomaat",
  "Jüri Konsumi pakiautomaat",
  "Kadrina Konsumi pakiautomaat",
  "Karksi-Nuia pakiautomaat",
  "Kehra pakiautomaat",
  "Kehtna A ja O pakiautomaat",
  "Keila Grossi pakiautomaat",
  "Keila Maxima pakiautomaat",
  "Keila Rõõmu kaubamaja pakiautomaat",
  "Kiili Konsumi pakiautomaat",
  "Kiisa A ja O pakiautomaat",
  "Kilingi-Nõmme Konsumi pakiautomaat",
  "Kiviõli Grossi pakiautomaat",
  "Kiviõli Maxima pakiautomaat",
  "Koeru Vallamaja pakiautomaat",
  "Kohila Konsumi pakiautomaat",
  "Kohtla-Järve Ahtme Maxima pakiautomaat",
  "Kohtla-Järve Keskallee Maxima pakiautomaat",
  "Kohtla-Järve Mõisa tee Maxima pakiautomaat",
  "Kohtla-Järve Rimi pakiautomaat",
  "Kohtla-Järve Vironia keskuse pakiautomaat",
  "Kose Grossi pakiautomaat",
  "Kostivere Meie kaupluse pakiautomaat",
  "Kunda Grossi pakiautomaat",
  "Kuressaare Maxima XX pakiautomaat",
  "Kuressaare Smuuli pakiautomaat",
  "Kuusalu pakiautomaat",
  "Käina Konsumi pakiautomaat",
  "Kärdla Hiiu Konsumi pakiautomaat",
  "Kärdla Tormi Konsumi pakiautomaat",
  "Kõrveküla A ja O pakiautomaat",
  "Laagri CoMarketi pakiautomaat",
  "Laagri Maksimarketi pakiautomaat",
  "Lagedi Keskusehoone pakiautomaat",
  "Lihula Konsumi pakiautomaat",
  "Loksa Grossi pakiautomaat",
  "Loo Grossi pakiautomaat",
  "Maardu Maxima X pakiautomaat",
  "Maardu Maxima XX pakiautomaat",
  "Maardu Pärli Keskuse pakiautomaat",
  "Muhu Liiva Alexela pakiautomaat",
  "Muraste Konsumi pakiautomaat",
  "Mustvee Konsumi pakiautomaat",
  "Muuga Maxima pakiautomaat",
  "Märjamaa Maxima pakiautomaat",
  "Narva Astri Keskuse pakiautomaat",
  "Narva Fama keskuse pakiautomaat",
  "Narva Kerese keskuse pakiautomaat",
  "Narva Kreenholmi Maxima XX pakiautomaat",
  "Narva Megamarketi pakiautomaat",
  "Narva Prisma pakiautomaat",
  "Narva Tiimani Maxima XX pakiautomaat",
  "Narva-Jõesuu raamatukogu pakiautomaat",
  "Nõo vallamaja pakiautomaat",
  "Orissaare pakiautomaat",
  "Otepää Maxima pakiautomaat",
  "Paide Hesburgeri pakiautomaat",
  "Paide Selveri pakiautomaat",
  "Paikuse Konsumi pakiautomaat",
  "Paldiski Konsumi pakiautomaat",
  "Paldiski Maxima X pakiautomaat",
  "Peetri Keskuse pakiautomaat",
  "Peetri Selveri pakiautomaat",
  "Puhja Coop kaupluse pakiautomaat",
  "Pärnu Jannseni Rimi pakiautomaat",
  "Pärnu Kaubamajaka pakiautomaat",
  "Pärnu Maksimarketi pakiautomaat",
  "Pärnu Maxima pakiautomaat",
  "Pärnu Oja Comarketi pakiautomaat",
  "Pärnu Port Artur 2 pakiautomaat",
  "Pärnu Tiina Konsumi pakiautomaat",
  "Pärnu Turu pakiautomaat",
  "Pärnu Ülejõe Selveri pakiautomaat",
  "Pärnu-Jaagupi pakiautomaat",
  "Põltsamaa Selveri pakiautomaat",
  "Põlva Kaubamaja pakiautomaat",
  "Põlva Meie kaupluse pakiautomaat",
  "Põlva Selveri pakiautomaat",
  "Raasiku pakiautomaat",
  "Rakvere Lilleoru kaupluse pakiautomaat",
  "Rakvere Põhjakeskuse pakiautomaat",
  "Rakvere Turutare pakiautomaat",
  "Rakvere Vaala Keskuse pakiautomaat",
  "Rapla Maxima pakiautomaat",
  "Rapla Vestis Konsumi pakiautomaat",
  "Risti vallamaja pakiautomaat",
  "Räpina Konsumi pakiautomaat",
  "Räpina Maxima pakiautomaat",
  "Rõngu Coop kaupluse pakiautomaat",
  "Saaremaa Kaubamaja pakiautomaat",
  "Saku Konsumi pakiautomaat",
  "Saku Selveri pakiautomaat",
  "Salme Rannapargi tee pakiautomaat",
  "Saue Grossi pakiautomaat",
  "Saue Kaubakeskuse pakiautomaat",
  "Sauga Coop kaupluse pakiautomaat",
  "Sillamäe Maksimarketi pakiautomaat",
  "Sillamäe Viru pst Maxima pakiautomaat",
  "Sindi Maxima pakiautomaat",
  "Suure-Jaani pakiautomaat",
  "Tabasalu Rimi pakiautomaat",
  "Tabivere Saadjärve A ja O pakiautomaat",
  "Tallinna Akadeemia Konsumi pakiautomaat",
  "Tallinna Arsenali Keskuse pakiautomaat",
  "Tallinna Balti Jaama pakiautomaat",
  "Tallinna Coca-Cola Plaza pakiautomaat",
  "Tallinna Ehitajate tee Grossi pakiautomaat",
  "Tallinna Ehitajate tee Maxima XXX pakiautomaat",
  "Tallinna Haabersti Rimi pakiautomaat",
  "Tallinna Idakeskuse pakiautomaat",
  "Tallinna Juhkentali Rimi pakiautomaat",
  "Tallinna Järve Keskuse pakiautomaat",
  "Tallinna Järveotsa Grossi pakiautomaat",
  "Tallinna Kadaka Selveri pakiautomaat",
  "Tallinna Kakumäe Selveri pakiautomaat",
  "Tallinna Kari Grossipoe pakiautomaat",
  "Tallinna Kivila Grossi pakiautomaat",
  "Tallinna Kolde Rimi pakiautomaat",
  "Tallinna Kollase keskuse pakiautomaat",
  "Tallinna Kristiine Keskuse pakiautomaat",
  "Tallinna Kärberi Keskuse pakiautomaat",
  "Tallinna Lasnamäe Centrumi A pakiautomaat",
  "Tallinna Lasnamäe Centrumi B pakiautomaat",
  "Tallinna Lasnamäe Prisma pakiautomaat",
  "Tallinna Lastekodu Grossi pakiautomaat",
  "Tallinna Lauluväljaku Maxima pakiautomaat",
  "Tallinna Linnamäe Maxima XXX pakiautomaat",
  "Tallinna Läänemere Rimi pakiautomaat",
  "Tallinna Läänemere Selveri pakiautomaat",
  "Tallinna Magdaleena pakiautomaat",
  "Tallinna Magistrali Keskuse pakiautomaat",
  "Tallinna Marienthali keskuse pakiautomaat",
  "Tallinna Merimetsa Selveri pakiautomaat",
  "Tallinna Mustakivi Keskuse pakiautomaat",
  "Tallinna Mustamäe Keskuse pakiautomaat",
  "Tallinna Mustika Keskuse pakiautomaat",
  "Tallinna Männiku Rimi pakiautomaat",
  "Tallinna Nautica Keskuse pakiautomaat",
  "Tallinna Nurmenuku pakiautomaat",
  "Tallinna Nõmme tee 23 Maxima pakiautomaat",
  "Tallinna Nõmme turu pakiautomaat",
  "Tallinna Paasiku Grossi pakiautomaat",
  "Tallinna Paepargi Maxima XX pakiautomaat",
  "Tallinna Pallasti pakiautomaat",
  "Tallinna Pelgulinna Selveri pakiautomaat",
  "Tallinna Peterburi tee 34/4 pakiautomaat",
  "Tallinna Peterburi tee Rimi pakiautomaat",
  "Tallinna Pirita Keskuse pakiautomaat",
  "Tallinna Pirita Selveri pakiautomaat",
  "Tallinna Punase Selveri pakiautomaat",
  "Tallinna Pärnu mnt 390b Maxima pakiautomaat",
  "Tallinna Pääsküla RIMI pakiautomaat",
  "Tallinna Põhja pst Neste pakiautomaat",
  "Tallinna Raudalu Konsumi pakiautomaat",
  "Tallinna Rocca al Mare pakiautomaat",
  "Tallinna Sikupilli pakiautomaat",
  "Tallinna Solaris Keskuse pakiautomaat",
  "Tallinna Stockmanni pakiautomaat",
  "Tallinna Stroomi Keskuse pakiautomaat",
  "Tallinna Sõle Rimi (Paavli 10) pakiautomaat",
  "Tallinna Sõpruse Rimi pakiautomaat",
  "Tallinna Sõpruse pst 171 Maxima pakiautomaat",
  "Tallinna Sütiste Maxima X pakiautomaat",
  "Tallinna T1 Keskuse pakiautomaat",
  "Tallinna Tammsaare Maxima XX pakiautomaat",
  "Tallinna Tammsaare Ärikeskuse pakiautomaat",
  "Tallinna Tatari Rimi pakiautomaat",
  "Tallinna Telliskivi Rimi pakiautomaat",
  "Tallinna Tondi Selveri pakiautomaat",
  "Tallinna Tondi Ärikeskuse pakiautomaat",
  "Tallinna Torupilli Selveri pakiautomaat",
  "Tallinna Tähesaju Selveri pakiautomaat",
  "Tallinna Tööstuse Rimi pakiautomaat",
  "Tallinna Valdeku CoMarketi pakiautomaat",
  "Tallinna Valdeku Maxima pakiautomaat",
  "Tallinna Vikerlase Rimi pakiautomaat",
  "Tallinna Vilde tee Maxima pakiautomaat",
  "Tallinna Viru Bussiterminali pakiautomaat",
  "Tallinna Viru Keskuse pakiautomaat",
  "Tallinna Õismäe Maxima XX pakiautomaat",
  "Tallinna Ülemiste City Selveri pakiautomaat",
  "Tallinna Ülemiste keskuse pakiautomaat",
  "Tallinna Ümera Maxima pakiautomaat",
  "Tamsalu Grossi pakiautomaat",
  "Tapa Grossi pakiautomaat",
  "Tapa Maxima pakiautomaat",
  "Tartu Aardla Selveri pakiautomaat",
  "Tartu Anne 40 Maxima pakiautomaat",
  "Tartu Anne Selveri pakiautomaat",
  "Tartu Eedeni pakiautomaat",
  "Tartu Ilmatsalu Maxima pakiautomaat",
  "Tartu Jaamamõisa Selveri pakiautomaat",
  "Tartu Karete Konsumi pakiautomaat",
  "Tartu Kesklinna Keskuse pakiautomaat",
  "Tartu Kivilinna pakiautomaat",
  "Tartu Kvartali Keskuse pakiautomaat",
  "Tartu Lembitu Konsumi pakiautomaat",
  "Tartu Lõunakeskuse pakiautomaat",
  "Tartu Raadi Maxima pakiautomaat",
  "Tartu Rebase Rimi pakiautomaat",
  "Tartu Ringtee Selveri pakiautomaat",
  "Tartu Saare Maxima pakiautomaat",
  "Tartu Sõbra Prisma pakiautomaat",
  "Tartu Sõbrakeskuse pakiautomaat",
  "Tartu Tasku keskuse pakiautomaat",
  "Tartu Tuglase Rimi pakiautomaat",
  "Tartu Ujula Konsumi pakiautomaat",
  "Tartu Vahi Selveri pakiautomaat",
  "Tartu Veeriku Selveri pakiautomaat",
  "Tartu Zeppelini pakiautomaat",
  "Torma A ja O pakiautomaat",
  "Turba kaupluse pakiautomaat",
  "Tõrva Maxima pakiautomaat",
  "Tõrvandi Konsumi pakiautomaat",
  "Türi Maxima pakiautomaat",
  "Valga Maxima pakiautomaat",
  "Valga Siili Konsumi pakiautomaat",
  "Vastse-Kuuste A ja O pakiautomaat",
  "Viimsi Kaubanduskeskuse pakiautomaat",
  "Viimsi Pärnamäe Rimi pakiautomaat",
  "Viimsi Rimi pakiautomaat",
  "Viljandi Bussijaama pakiautomaat",
  "Viljandi Maksimarketi pakiautomaat",
  "Viljandi Männimäe Selveri pakiautomaat",
  "Viljandi Tallinna 60 Maxima pakiautomaat",
  "Viljandi Vaksali Maxima X pakiautomaat",
  "Vinni Spordikompleksi pakiautomaat",
  "Väike-Maarja pakiautomaat",
  "Vändra Konsumi pakiautomaat",
  "Vääna-Jõesuu kauplus Maksis pakiautomaat",
  "Võru Maksimarketi pakiautomaat",
  "Võru Maxima pakiautomaat",
  "Võru kesklinna Circle K pakiautomaat",
  "Ülenurme Konsumi pakiautomaat"
];
